// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_JnvuyyUPLleXZqB4W0Ny2eRt1WID0Qc',
    appId: '1:688033894735:web:01b7da8ad6b5e5f8bfb53a',
    messagingSenderId: '688033894735',
    projectId: 'dappfinal-899fc',
    authDomain: 'dappfinal-899fc.firebaseapp.com',
    storageBucket: 'dappfinal-899fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc1PTWlO9-q-ZIi53uvArR3EOKY4iDnM8',
    appId: '1:688033894735:android:1c6615fd6e638052bfb53a',
    messagingSenderId: '688033894735',
    projectId: 'dappfinal-899fc',
    storageBucket: 'dappfinal-899fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnafB2xFntgSO5a8EuyMiOwjDPd6782Y',
    appId: '1:688033894735:ios:d7b47861570e9859bfb53a',
    messagingSenderId: '688033894735',
    projectId: 'dappfinal-899fc',
    storageBucket: 'dappfinal-899fc.appspot.com',
    iosBundleId: 'com.example.shareable3dviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZnafB2xFntgSO5a8EuyMiOwjDPd6782Y',
    appId: '1:688033894735:ios:fd272cccc08d54debfb53a',
    messagingSenderId: '688033894735',
    projectId: 'dappfinal-899fc',
    storageBucket: 'dappfinal-899fc.appspot.com',
    iosBundleId: 'com.example.shareable3dviewer.RunnerTests',
  );
}
